import 'stop-runaway-react-effects/hijack'
import './test/server'
import 'bootstrap/dist/css/bootstrap-reboot.css'
import '@reach/dialog/styles.css'
import '@reach/menu-button/styles.css'
import '@reach/tooltip/styles.css'
import './styles/global.css'
